### ISSUE TITLE
feat: Implement primitives for a subset of data processing

### ISSUE THREAD

**Issue by saboenisa** [pvs-hd-tea/LapsPython#12]
We have to write the primitives for a selection of data processing functions **(pandas)**.

**Comment by chbridges** [comment]
Questionable whether this will actually work because LAPS uses its own data types and primitives need to be implemented in Python and OCaml. Processing of pandas dataframes possible?

**Comment by chbridges** [comment]
Probably not doable, but we can research further if we have time.
