### ISSUE TITLE
feat: Extract implementations of primitives as strings for translation

### ISSUE THREAD

**Issue by saboenisa** [pvs-hd-tea/LapsPython#2]
**The idea is to create a dictionary.** 

Example: 

https://github.com/ellisk42/ec/blob/icml_2021_supplement/dreamcoder/domains/re2/re2Primitives.py

Extract implementations as strings and add them to a dictionary. This way we can access the primitives and write their implementations into a code file during translation

**Comment by chbridges** [comment]
cf. branch [feat/extraction-primitives](https://github.com/pvs-hd-tea/LapsPython/tree/feat/extraction-primitives)

Functions and tests are implemented, but not yet evaluated on real code

**Comment by chbridges** [comment]
Functions and tests are implemented and extended to resolve lambda functions, evaluated on dummy code.
